# Parametri configurazione SSL
# Crea una nuova chiave auto-firmata con:
#   keytool -genkeypair -keyalg RSA -alias selfsigned -keystore <name> -storepass <password> -validity 360 -keysize 2048
# Modifica poi i valori sottostanti
ssl:
  active: true
  password: "banlist"
  name: "key.jks"

# Percorsi in cui mostrare l'output
output:
  path:
    ban: "/ban"
    freeze: "/freeze"
    onlinePlayers: "/online"
    offlinePlayers: "/offline"
    essentials:
      mute: "/mute"
      jail: "/jail"
    vault:
      permissions: "/permissions"
      economy: "/economy"
  port: 80

# Cosa devo mostrare?
show:
  ban:
    byIP: true
    byNAME: true
  essentials:
    mute: true
    jail:
      jailed: true
      jails: true
  freeze: true
  onlinePlayers: true
  offlinePlayers: true
  vault:
    permissions: true
    economy:
      banks: true
      balances: true
