# Percorsi in cui mostrare l'output
output:
  path:
    ban: "/ban"
    freeze: "/freeze"
    essentials:
      mute: "/mute"
      jail: "/jail"
    vault:
      permissions: "/permissions"
      economy: "/economy"
  port: 80

# Cosa devo mostrare?
show:
  ban:
    byIP: true
    byNAME: true
  essentials:
    mute: true
    jail:
      jailed: true
      jails: true
  freeze: true
  vault:
    permissions: true
    economy:
      banks: true
      balances: true
