# Percorsi in cui mostrare l'output
output:
  path:
    ban: "/ban"
    mute: "/mute"
    freeze: "/freeze"
    perms: "/perms"
    economy: "/economy"
  port: 80

# Cosa devo mostrare?
show:
  ban:
    byIP: true
    byNAME: true
  mute: true
  freeze: true
  perms: true
  economy:
    banks: true
    balances: true
