# Parametri configurazione SSL
# Crea una nuova chiave auto-firmata con:
#   keytool -genkeypair -keyalg RSA -alias selfsigned -keystore <name> -storepass <password> -validity 360 -keysize 2048
# Modifica poi i valori sottostanti
ssl:
  active: true
  password: "banlist"
  name: "key.jks"

# Percorsi in cui mostrare l'output
output:
  path:
    ban: "/ban"
    onlinePlayers: "/online"
    permissions: "/permissions"
    scoreboard: "/points"
  port: 80

# Cosa devo mostrare?
show:
  ban:
    byIP: false
    byNAME: false
  onlinePlayers: true
  permissions: true
  scoreboard: true
