main: it.marko.banlist.BanList
name: "BanList"
version: "1.2"
author: "MemoryOfLife"
website: "https://github.com/rospino74/BanList/"
description: "Restituisce in formato JSON la lista dei ban e mute"
api-version: "1.15"
softdepend:
  - Essentials
  - Freezer
  - Valut
