main: ${main}
name: "DataList"
version: ${version}
author: ${author}
website: "https://github.com/BuildTheEarth-Italia/DataList/"
description: "Restituisce in formato JSON la lista dei ban e mute"
#api-version: "1.12"
softdepend:
  - Vault
